import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

import { BiCodeAlt, BiCodeCurly } from 'react-icons/bi'
import { DiJava, DiJavascript1 } from 'react-icons/di'
import { FaReact, FaVuejs } from 'react-icons/fa'
import { SiRedux } from 'react-icons/si'
import { TbBrandReactNative } from 'react-icons/tb'

import Header from '@/components/header'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Home | Next</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main className='container m-auto px-5'>
				<section className='px-80 max-2xl:px-72 max-xl:px-48 max-lg:px-28 max-md:px-10 max-sm:px-0 || mt-24 max-lg:mt-16 max-sm:mt-10 || relative'>
					<div className="absolute z-[-1] top-10 right-3/4"><BiCodeAlt color='#999' size={30} /></div>
					<div className="absolute z-[-1] top-32 left-3/4"><BiCodeCurly color='#80137c' size={30} /></div>
					<div className="absolute z-[-1] -top-7 left-2/4 max-sm:left-3/4"><DiJavascript1 color='yellow' size={30} /></div>
					<div className="absolute z-[-1] bottom-10 left-[28%] max-md:left-[10%] max-md:bottom-14"><FaReact color='#3974f4' size={30} /></div>
					<div className="absolute z-[-1] -bottom-7 right-1/3"><FaVuejs color='#03540a' size={30} /></div>
					<h1 className='text-5xl max-lg:text-4xl max-md:text-2xl font-bold text-white text-center tracking-[.2rem]'>BECOME A DEMANDED SPECIALIST</h1>
					<p className='text-gray-400 text-center mt-5 max-md:text-sm'>A few months and you are a ready-to-work specialist. Available. Qualitatively. According to the authors methods and constant contact with the teacher.</p>
					<div className="flex justify-center gap-5 mt-5">
						<button type="button" className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Go to personal account</button>
						<button type="button" className="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Free lesson</button>
					</div>
				</section>

				<section className='flex max-md:flex-col-reverse || mt-40 max-lg:mt-32 max-md:mt-20 || gap-10'>
					<div className="">
						<p className='text-2xl max-md:text-xl || text-gray-400'>Lorem, ipsum dolor.</p>
						<h1 className='text-5xl max-lg:text-4xl max-md:text-3xl || text-white mt-5 font-normal tracking-[0.56px]'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Delectus, dicta!</h1>
					</div>
					<div className="">
						<p className='text-3xl max-lg:text-2xl || tracking-[0.64px] text-white'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
						<p className='text-lg max-md:text-base || mt-9 max-md:mt-5 || text-gray-400'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
						<div className="flex justify-around mt-5 text-gray-100">
							<div className="flex flex-col items-center"><DiJava color='#d96902' size={30} /> <p>Java</p></div>
							<div className="flex flex-col items-center"><SiRedux color='#7046b2' size={30} /> <p>Redux</p></div>
							<div className="flex flex-col items-center"><TbBrandReactNative color='#1af2f2' size={30} /> <p>React Native</p></div>
						</div>
					</div>
				</section>

				<section className='mt-40 max-lg:mt-32 max-md:mt-20'>
					<div className="text-center">
						<h2 className='text-5xl max-lg:text-3xl || text-white'>Lorem</h2>
						<p className='text-lg text-gray-400 mt-5'>Lorem ipsum dolor sit amet.</p>
					</div>
					<div className="mt-20 max-md:mt-14 || flex flex-col gap-10">
						<div className="flex max-md:flex-col-reverse || justify-between w-full gap-10">
							<div className="w-[45%] max-md:w-full">
								<img src="https://images.unsplash.com/photo-1594069758873-e79e9075eb7d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80" alt="" />
							</div>
							<div className="flex flex-col justify-around || w-[50%] max-md:w-full">
								<p className='text-lg text-white bg-orange-400 w-fit py-2 px-3 mb-5 '>Lorem, ipsum.</p>
								<p className='text-5xl max-lg:text-3xl max-sm:text-2xl || text-gray-400'>Lorem ipsum dolor sit amet.</p>
								<span className='text-xl text-gray-600'>Read More</span>
							</div>
						</div>

						<div className="flex max-md:flex-col || justify-between w-full gap-10">
							<div className="flex flex-col justify-around || w-[50%] max-md:w-full">
								<p className='text-lg text-white bg-orange-400 w-fit py-2 px-3 mb-5 '>Lorem, ipsum.</p>
								<p className='text-5xl max-lg:text-3xl max-sm:text-2xl || text-gray-400'>Lorem ipsum dolor sit amet.</p>
								<span className='text-xl text-gray-600'>Read More</span>
							</div>
							<div className="w-[45%] max-md:w-full">
								<img src="https://images.unsplash.com/photo-1594069758873-e79e9075eb7d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80" alt="" />
							</div>
						</div>

						<div className="flex max-md:flex-col-reverse || justify-between w-full gap-10">
							<div className="w-[45%] max-md:w-full">
								<img src="https://images.unsplash.com/photo-1594069758873-e79e9075eb7d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80" alt="" />
							</div>
							<div className="flex flex-col justify-around || w-[50%] max-md:w-full">
								<p className='text-lg text-white bg-orange-400 w-fit py-2 px-3 mb-5 '>Lorem, ipsum.</p>
								<p className='text-5xl max-lg:text-3xl max-sm:text-2xl || text-gray-400'>Lorem ipsum dolor sit amet.</p>
								<span className='text-xl text-gray-600'>Read More</span>
							</div>
						</div>

						<div className="flex max-md:flex-col || justify-between w-full gap-10">
							<div className="flex flex-col justify-around || w-[50%] max-md:w-full">
								<p className='text-lg text-white bg-orange-400 w-fit py-2 px-3 mb-5 '>Lorem, ipsum.</p>
								<p className='text-5xl max-lg:text-3xl max-sm:text-2xl || text-gray-400'>Lorem ipsum dolor sit amet.</p>
								<span className='text-xl text-gray-600'>Read More</span>
							</div>
							<div className="w-[45%] max-md:w-full">
								<img src="https://images.unsplash.com/photo-1594069758873-e79e9075eb7d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80" alt="" />
							</div>
						</div>
					</div>
				</section>
			</main>
			<Footer />
		</>
	)
}
